const state = {
  selectedUserIds: [],
  users: [
    {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      birthDate: "1988-02-25",
      quote: "Hello World!",
      profession_id: 1,
      country_id: 1,
    },
    {
      id: 2,
      firstName: "Jane",
      lastName: "Smith",
      birthDate: "1990-06-15",
      quote: "Live and let live.",
      profession_id: 2,
      country_id: 2,
    },
    {
      id: 3,
      firstName: "Michael",
      lastName: "Johnson",
      birthDate: "1985-11-30",
      quote: "Never give up!",
      profession_id: 3,
      country_id: 3,
    },
    {
      id: 4,
      firstName: "Emily",
      lastName: "Davis",
      birthDate: "1992-03-10",
      quote: "Carpe Diem!",
      profession_id: 4,
      country_id: 1,
    },
    {
      id: 5,
      firstName: "Chris",
      lastName: "Brown",
      birthDate: "1980-01-22",
      quote: "Stay positive.",
      profession_id: 2,
      country_id: 2,
    },
    {
      id: 6,
      firstName: "Jessica",
      lastName: "Taylor",
      birthDate: "1995-07-07",
      quote: "Believe in yourself.",
      profession_id: 3,
      country_id: 3,
    },
    {
      id: 7,
      firstName: "Matthew",
      lastName: "Wilson",
      birthDate: "1978-12-16",
      quote: "The best is yet to come.",
      profession_id: 4,
      country_id: 1,
    },
    {
      id: 8,
      firstName: "Sarah",
      lastName: "Moore",
      birthDate: "1993-09-05",
      quote: "Make today count.",
      profession_id: 2,
      country_id: 2,
    },
    {
      id: 9,
      firstName: "David",
      lastName: "Anderson",
      birthDate: "1987-04-12",
      quote: "Be the change.",
      profession_id: 3,
      country_id: 3,
    },
    {
      id: 10,
      firstName: "Laura",
      lastName: "Thomas",
      birthDate: "1991-08-28",
      quote: "Dream big.",
      profession_id: 4,
      country_id: 1,
    },
    {
      id: 11,
      firstName: "Daniel",
      lastName: "Harris",
      birthDate: "1989-05-14",
      quote: "Stay hungry, stay foolish.",
      profession_id: 1,
      country_id: 2,
    },
    {
      id: 12,
      firstName: "Olivia",
      lastName: "Clark",
      birthDate: "1994-10-02",
      quote: "Embrace the journey.",
      profession_id: 2,
      country_id: 3,
    },
    {
      id: 13,
      firstName: "James",
      lastName: "Rodriguez",
      birthDate: "1982-03-25",
      quote: "Keep pushing forward.",
      profession_id: 3,
      country_id: 1,
    },
    {
      id: 14,
      firstName: "Sophia",
      lastName: "Lewis",
      birthDate: "1990-12-30",
      quote: "Live your life.",
      profession_id: 4,
      country_id: 2,
    },
    {
      id: 15,
      firstName: "Ethan",
      lastName: "Lee",
      birthDate: "1985-08-18",
      quote: "Find your passion.",
      profession_id: 1,
      country_id: 3,
    },
    {
      id: 16,
      firstName: "Ava",
      lastName: "Walker",
      birthDate: "1996-04-05",
      quote: "Be fearless.",
      profession_id: 2,
      country_id: 1,
    },
    {
      id: 17,
      firstName: "William",
      lastName: "Hall",
      birthDate: "1981-11-23",
      quote: "Dream without fear.",
      profession_id: 3,
      country_id: 2,
    },
    {
      id: 18,
      firstName: "Isabella",
      lastName: "Young",
      birthDate: "1992-05-07",
      quote: "Choose happiness.",
      profession_id: 4,
      country_id: 3,
    },
    {
      id: 19,
      firstName: "Alexander",
      lastName: "King",
      birthDate: "1987-09-11",
      quote: "Make it happen.",
      profession_id: 1,
      country_id: 1,
    },
    {
      id: 20,
      firstName: "Mia",
      lastName: "Scott",
      birthDate: "1993-02-14",
      quote: "Live life to the fullest.",
      profession_id: 2,
      country_id: 2,
    },
  ],
};

export default state;
